/**
 * HERRE-COL — catalog data model.
 * Data-driven: add a category to CATEGORIES and designs to DESIGNS.
 * Every design belongs to a category by its `cat` slug — nothing else needs to change.
 *
 * Image paths point to assets/cat/... . Drop real product photos at these exact
 * paths and they will appear automatically; until then a branded placeholder is
 * shown (see js/placeholder.js).
 */

export const CATEGORIES = [
  { slug: 'puertas', name: 'Puertas', icon: 'door-closed', tagline: 'El primer gesto de una fachada.' },
  { slug: 'ventanas', name: 'Ventanas', icon: 'app-window', tagline: 'Luz enmarcada con precisión.' },
  { slug: 'ventanales', name: 'Ventanales', icon: 'panels-top-left', tagline: 'Vidrio y acero de piso a techo.' },
  { slug: 'puertas-reja', name: 'Puertas Reja', icon: 'shield-half', tagline: 'Seguridad que se ve elegante.' },
  { slug: 'enrejados', name: 'Enrejados', icon: 'fence', tagline: 'Ritmo, línea y protección.' },
  { slug: 'portones', name: 'Portones', icon: 'warehouse', tagline: 'La entrada que impone respeto.' },
  { slug: 'escaleras', name: 'Escaleras y Pasamanos', icon: 'chevrons-up', tagline: 'Estructura convertida en escultura.' },
  { slug: 'cubiertas', name: 'Cubiertas y Marquesinas', icon: 'triangle', tagline: 'Sombra con intención arquitectónica.' },
  { slug: 'santamarias', name: 'Santamarías', icon: 'rows', tagline: 'Cierre seguro para locales y garajes.' },
  { slug: 'estantes', name: 'Estantes Metálicos', icon: 'library', tagline: 'Almacenamiento resistente y organizado.' },
  { slug: 'casilleros', name: 'Casilleros', icon: 'grid', tagline: 'Almacenamiento seguro en metal.' },
  { slug: 'exhibidores', name: 'Exhibidores', icon: 'shirt', tagline: 'Estructuras para exhibir tu producto.' },
  { slug: 'casetas-comedores', name: 'Casetas y Comedores Metálicos', icon: 'store', tagline: 'Espacios y mobiliario en metal a la medida.' },
];

const doorImg = (n) => `assets/cat/puertas/puerta-${n}.jpg`;

export const DESIGNS = [
  // Puertas
  { ref: 'PT-190', name: 'PT-190', cat: 'puertas', desc: '', img: doorImg('90') },
  { ref: 'PT-191', name: 'PT-191', cat: 'puertas', desc: '', img: doorImg('91') },
  { ref: 'PT-192', name: 'PT-192', cat: 'puertas', desc: '', img: doorImg('92') },
  { ref: 'PT-193', name: 'PT-193', cat: 'puertas', desc: '', img: doorImg('93') },
  { ref: 'PT-194', name: 'PT-194', cat: 'puertas', desc: '', img: doorImg('94') },
  { ref: 'PT-195', name: 'PT-195', cat: 'puertas', desc: '', img: doorImg('95') },
  { ref: 'PT-100', name: 'PT-100', cat: 'puertas', desc: '', img: doorImg('100') },
  { ref: 'PT-196', name: 'PT-196', cat: 'puertas', desc: '', img: doorImg('96') },
  { ref: 'PT-182', name: 'PT-182', cat: 'puertas', desc: '', img: doorImg('101') },
  { ref: 'PT-183', name: 'PT-183', cat: 'puertas', desc: '', img: doorImg('102') },
  { ref: 'PT-197', name: 'PT-197', cat: 'puertas', desc: '', img: doorImg('97') },
  { ref: 'PT-198', name: 'PT-198', cat: 'puertas', desc: '', img: doorImg('98') },
  { ref: 'PT-199', name: 'PT-199', cat: 'puertas', desc: '', img: doorImg('99') },
  { ref: 'PT-145', name: 'PT-145', cat: 'puertas', desc: '', img: doorImg('45') },
  { ref: 'PT-135', name: 'Acceso PT-135', cat: 'puertas', desc: '', img: doorImg('35') },
  { ref: 'PT-146', name: 'PT-146', cat: 'puertas', desc: '', img: doorImg('46') },
  { ref: 'PT-168', name: 'PT-168', cat: 'puertas', desc: '', img: doorImg('68') },
  { ref: 'PT-123', name: 'Moderna PT-123', cat: 'puertas', desc: '', img: doorImg('23') },
  { ref: 'PT-121', name: 'Entrada PT-121', cat: 'puertas', desc: '', img: doorImg('21') },
  { ref: 'PT-169', name: 'PT-169', cat: 'puertas', desc: '', img: doorImg('69') },
  { ref: 'PT-114', name: 'Seguridad PT-114', cat: 'puertas', desc: '', img: doorImg('14') },
  { ref: 'PT-170', name: 'PT-170', cat: 'puertas', desc: '', img: doorImg('70') },
  { ref: 'PT-151', name: 'PT-151', cat: 'puertas', desc: '', img: doorImg('51') },
  { ref: 'PT-153', name: 'PT-153', cat: 'puertas', desc: '', img: doorImg('53') },
  { ref: 'PT-171', name: 'PT-171', cat: 'puertas', desc: '', img: doorImg('71') },
  { ref: 'PT-113', name: 'Moderna PT-113', cat: 'puertas', desc: '', img: doorImg('13') },
  { ref: 'PT-154', name: 'PT-154', cat: 'puertas', desc: '', img: doorImg('54') },
  { ref: 'PT-156', name: 'PT-156', cat: 'puertas', desc: '', img: doorImg('56') },
  { ref: 'PT-172', name: 'PT-172', cat: 'puertas', desc: '', img: doorImg('72') },
  { ref: 'PT-133', name: 'Moderna PT-133', cat: 'puertas', desc: '', img: doorImg('33') },
  { ref: 'PT-159', name: 'PT-159', cat: 'puertas', desc: '', img: doorImg('59') },
  { ref: 'PT-173', name: 'PT-173', cat: 'puertas', desc: '', img: doorImg('73') },
  { ref: 'PT-161', name: 'PT-161', cat: 'puertas', desc: '', img: doorImg('61') },
  { ref: 'PT-162', name: 'PT-162', cat: 'puertas', desc: '', img: doorImg('62') },
  { ref: 'PT-164', name: 'PT-164', cat: 'puertas', desc: '', img: doorImg('64') },
  { ref: 'PT-174', name: 'PT-174', cat: 'puertas', desc: '', img: doorImg('74') },
  { ref: 'PT-165', name: 'PT-165', cat: 'puertas', desc: '', img: doorImg('65') },
  { ref: 'PT-166', name: 'PT-166', cat: 'puertas', desc: '', img: doorImg('66') },
  { ref: 'PT-101', name: 'Entrada PT-101', cat: 'puertas', desc: '', img: doorImg('01') },
  { ref: 'PT-175', name: 'PT-175', cat: 'puertas', desc: '', img: doorImg('75') },
  { ref: 'PT-102', name: 'Principal PT-102', cat: 'puertas', desc: '', img: doorImg('02') },
  { ref: 'PT-103', name: 'Moderna PT-103', cat: 'puertas', desc: '', img: doorImg('03') },
  { ref: 'PT-105', name: 'Acceso PT-105', cat: 'puertas', desc: '', img: doorImg('05') },
  { ref: 'PT-176', name: 'PT-176', cat: 'puertas', desc: '', img: doorImg('76') },
  { ref: 'PT-106', name: 'Diseño PT-106', cat: 'puertas', desc: '', img: doorImg('06') },
  { ref: 'PT-107', name: 'Contemporánea PT-107', cat: 'puertas', desc: '', img: doorImg('07') },
  { ref: 'PT-108', name: 'Insignia PT-108', cat: 'puertas', desc: '', img: doorImg('08') },
  { ref: 'PT-109', name: 'Vanguardia PT-109', cat: 'puertas', desc: '', img: doorImg('09') },
  { ref: 'PT-110', name: 'Élite PT-110', cat: 'puertas', desc: '', img: doorImg('10') },
  { ref: 'PT-112', name: 'Principal PT-112', cat: 'puertas', desc: '', img: doorImg('12') },
  { ref: 'PT-115', name: 'Acceso PT-115', cat: 'puertas', desc: '', img: doorImg('15') },
  { ref: 'PT-178', name: 'PT-178', cat: 'puertas', desc: '', img: doorImg('78') },
  { ref: 'PT-118', name: 'Insignia PT-118', cat: 'puertas', desc: '', img: doorImg('18') },
  { ref: 'PT-119', name: 'Vanguardia PT-119', cat: 'puertas', desc: '', img: doorImg('19') },
  { ref: 'PT-120', name: 'Élite PT-120', cat: 'puertas', desc: '', img: doorImg('20') },
  { ref: 'PT-122', name: 'Principal PT-122', cat: 'puertas', desc: '', img: doorImg('22') },
  { ref: 'PT-179', name: 'PT-179', cat: 'puertas', desc: '', img: doorImg('79') },
  { ref: 'PT-124', name: 'Seguridad PT-124', cat: 'puertas', desc: '', img: doorImg('24') },
  { ref: 'PT-128', name: 'Insignia PT-128', cat: 'puertas', desc: '', img: doorImg('28') },
  { ref: 'PT-130', name: 'Élite PT-130', cat: 'puertas', desc: '', img: doorImg('30') },
  { ref: 'PT-180', name: 'PT-180', cat: 'puertas', desc: '', img: doorImg('80') },
  { ref: 'PT-131', name: 'Entrada PT-131', cat: 'puertas', desc: '', img: doorImg('31') },
  { ref: 'PT-134', name: 'Seguridad PT-134', cat: 'puertas', desc: '', img: doorImg('34') },
  { ref: 'PT-136', name: 'Diseño PT-136', cat: 'puertas', desc: '', img: doorImg('36') },
  { ref: 'PT-181', name: 'PT-181', cat: 'puertas', desc: '', img: doorImg('81') },
  { ref: 'PT-137', name: 'Contemporánea PT-137', cat: 'puertas', desc: '', img: doorImg('37') },
  { ref: 'PT-141', name: 'Entrada PT-141', cat: 'puertas', desc: '', img: doorImg('41') },
  { ref: 'PT-142', name: 'Principal PT-142', cat: 'puertas', desc: '', img: doorImg('42') },
  // Ventanas
  { ref: 'VN-252', name: 'VN-252', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-52.jpg' },
  { ref: 'VN-253', name: 'VN-253', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-53.jpg' },
  { ref: 'VN-254', name: 'VN-254', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-54.jpg' },
  { ref: 'VN-255', name: 'VN-255', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-55.jpg' },
  { ref: 'VN-256', name: 'VN-256', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-56.jpg' },
  { ref: 'VN-257', name: 'VN-257', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-57.jpg' },
  { ref: 'VN-258', name: 'VN-258', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-58.jpg' },
  { ref: 'VN-259', name: 'VN-259', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-59.jpg' },
  { ref: 'VN-260', name: 'VN-260', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-60.jpg' },
  { ref: 'VN-261', name: 'VN-261', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-61.jpg' },
  { ref: 'VN-262', name: 'VN-262', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-62.jpg' },
  { ref: 'VN-263', name: 'VN-263', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-63.jpg' },
  { ref: 'VN-264', name: 'VN-264', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-64.jpg' },
  { ref: 'VN-238', name: 'VN-238', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-38.jpg' },
  { ref: 'VN-250', name: 'VN-250', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-50.jpg' },
  { ref: 'VN-251', name: 'VN-251', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-51.jpg' },
  { ref: 'VN-230', name: 'VN-230', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-30.jpg' },
  { ref: 'VN-237', name: 'VN-237', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-37.jpg' },
  { ref: 'VN-236', name: 'VN-236', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-36.jpg' },
  { ref: 'VN-225', name: 'VN-225', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-25.jpg' },
  { ref: 'VN-222', name: 'VN-222', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-22.jpg' },
  { ref: 'VN-226', name: 'VN-226', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-26.jpg' },
  { ref: 'VN-231', name: 'VN-231', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-31.jpg' },
  { ref: 'VN-214', name: 'VN-214', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-14.jpg' },
  { ref: 'VN-227', name: 'VN-227', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-27.jpg' },
  { ref: 'VN-207', name: 'VN-207', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-7.jpg' },
  { ref: 'VN-208', name: 'VN-208', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-8.jpg' },
  { ref: 'VN-211', name: 'VN-211', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-11.jpg' },
  { ref: 'VN-213', name: 'VN-213', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-13.jpg' },
  { ref: 'VN-215', name: 'VN-215', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-15.jpg' },
  { ref: 'VN-216', name: 'VN-216', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-16.jpg' },
  { ref: 'VN-217', name: 'VN-217', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-17.jpg' },
  { ref: 'VN-218', name: 'VN-218', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-18.jpg' },
  { ref: 'VN-219', name: 'VN-219', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-19.jpg' },
  { ref: 'VN-220', name: 'VN-220', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-20.jpg' },
  { ref: 'VN-221', name: 'VN-221', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-21.jpg' },
  { ref: 'VN-223', name: 'VN-223', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-23.jpg' },
  { ref: 'VN-224', name: 'VN-224', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-24.jpg' },
  { ref: 'VN-228', name: 'VN-228', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-28.jpg' },
  { ref: 'VN-229', name: 'VN-229', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-29.jpg' },
  { ref: 'VN-232', name: 'VN-232', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-32.jpg' },
  { ref: 'VN-233', name: 'VN-233', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-33.jpg' },
  { ref: 'VN-234', name: 'VN-234', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-34.jpg' },
  { ref: 'VN-235', name: 'VN-235', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-35.jpg' },
  { ref: 'VN-205', name: 'VN-205', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-5.jpg' },
  // Puertas Reja
  { ref: 'PR-332', name: 'PR-332', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-32.jpg' },
  { ref: 'PR-306', name: 'PR-306', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-6.jpg' },
  { ref: 'PR-304', name: 'PR-304', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-4.jpg' },
  { ref: 'PR-305', name: 'PR-305', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-5.jpg' },
  { ref: 'PR-307', name: 'PR-307', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-7.jpg' },
  { ref: 'PR-308', name: 'PR-308', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-8.jpg' },
  { ref: 'PR-309', name: 'PR-309', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-9.jpg' },
  { ref: 'PR-310', name: 'PR-310', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-10.jpg' },
  { ref: 'PR-311', name: 'PR-311', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-11.jpg' },
  { ref: 'PR-312', name: 'PR-312', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-12.jpg' },
  { ref: 'PR-313', name: 'PR-313', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-13.jpg' },
  { ref: 'PR-314', name: 'PR-314', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-14.jpg' },
  { ref: 'PR-315', name: 'PR-315', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-15.jpg' },
  { ref: 'PR-316', name: 'PR-316', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-16.jpg' },
  { ref: 'PR-317', name: 'PR-317', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-17.jpg' },
  { ref: 'PR-318', name: 'PR-318', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-18.jpg' },
  { ref: 'PR-319', name: 'PR-319', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-19.jpg' },
  { ref: 'PR-320', name: 'PR-320', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-20.jpg' },
  { ref: 'PR-321', name: 'PR-321', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-21.jpg' },
  { ref: 'PR-322', name: 'PR-322', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-22.jpg' },
  { ref: 'PR-330', name: 'PR-330', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-30.jpg' },
  { ref: 'PR-331', name: 'PR-331', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-31.jpg' },
  { ref: 'PR-333', name: 'PR-333', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-33.jpg' },
  { ref: 'PR-334', name: 'PR-334', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-34.jpg' },
  { ref: 'PR-335', name: 'PR-335', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-35.jpg' },
  { ref: 'PR-336', name: 'PR-336', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-36.jpg' },
  { ref: 'PR-337', name: 'PR-337', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/reja-37.jpg' },
  // Enrejados
  { ref: 'EN-413', name: 'EN-413', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-13.jpg' },
  { ref: 'EN-401', name: 'EN-401', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-1.jpg' },
  { ref: 'EN-403', name: 'EN-403', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-3.jpg' },
  { ref: 'EN-404', name: 'EN-404', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-4.jpg' },
  { ref: 'EN-405', name: 'EN-405', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-5.jpg' },
  { ref: 'EN-407', name: 'EN-407', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-7.jpg' },
  { ref: 'EN-408', name: 'EN-408', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-8.jpg' },
  { ref: 'EN-409', name: 'EN-409', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-9.jpg' },
  { ref: 'EN-410', name: 'EN-410', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-10.jpg' },
  { ref: 'EN-412', name: 'EN-412', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-12.jpg' },
  { ref: 'EN-414', name: 'EN-414', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-14.jpg' },
  { ref: 'EN-415', name: 'EN-415', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-15.jpg' },
  { ref: 'EN-416', name: 'EN-416', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-16.jpg' },
  { ref: 'EN-417', name: 'EN-417', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-17.jpg' },
  { ref: 'EN-418', name: 'EN-418', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-18.jpg' },
  { ref: 'EN-419', name: 'EN-419', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-19.jpg' },
  { ref: 'EN-420', name: 'EN-420', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-20.jpg' },
  { ref: 'EN-421', name: 'EN-421', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-21.jpg' },
  { ref: 'EN-422', name: 'EN-422', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-22.jpg' },
  { ref: 'EN-423', name: 'EN-423', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-23.jpg' },
  { ref: 'EN-424', name: 'EN-424', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-24.jpg' },
  { ref: 'EN-425', name: 'EN-425', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-25.jpg' },
  { ref: 'EN-426', name: 'EN-426', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-26.jpg' },
  { ref: 'EN-427', name: 'EN-427', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-27.jpg' },
  { ref: 'EN-428', name: 'EN-428', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-28.jpg' },
  { ref: 'EN-429', name: 'EN-429', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-29.jpg' },
  { ref: 'EN-430', name: 'EN-430', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-30.jpg' },
  { ref: 'EN-431', name: 'EN-431', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-31.jpg' },
  // Portones
  { ref: 'PO-520', name: 'PO-520', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-20.jpg' },
  { ref: 'PO-523', name: 'PO-523', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-23.jpg' },
  { ref: 'PO-501', name: 'PO-501', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-1.jpg' },
  { ref: 'PO-502', name: 'PO-502', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-2.jpg' },
  { ref: 'PO-503', name: 'PO-503', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-3.jpg' },
  { ref: 'PO-504', name: 'PO-504', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-4.jpg' },
  { ref: 'PO-505', name: 'PO-505', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-5.jpg' },
  { ref: 'PO-506', name: 'PO-506', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-6.jpg' },
  { ref: 'PO-507', name: 'PO-507', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-7.jpg' },
  { ref: 'PO-508', name: 'PO-508', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-8.jpg' },
  { ref: 'PO-509', name: 'PO-509', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-9.jpg' },
  { ref: 'PO-510', name: 'PO-510', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-10.jpg' },
  { ref: 'PO-511', name: 'PO-511', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-11.jpg' },
  { ref: 'PO-512', name: 'PO-512', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-12.jpg' },
  { ref: 'PO-513', name: 'PO-513', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-13.jpg' },
  { ref: 'PO-514', name: 'PO-514', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-14.jpg' },
  { ref: 'PO-515', name: 'PO-515', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-15.jpg' },
  { ref: 'PO-517', name: 'PO-517', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-17.jpg' },
  { ref: 'PO-519', name: 'PO-519', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-19.jpg' },
  { ref: 'PO-521', name: 'PO-521', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-21.jpg' },
  { ref: 'PO-522', name: 'PO-522', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-22.jpg' },
  // Escaleras y Pasamanos
  { ref: 'ES-604', name: 'ES-604', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-4.jpg' },
  { ref: 'ES-620', name: 'ES-620', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-20.jpg' },
  { ref: 'ES-621', name: 'ES-621', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-21.jpg' },
  { ref: 'ES-605', name: 'ES-605', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-5.jpg' },
  { ref: 'ES-606', name: 'ES-606', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-6.jpg' },
  { ref: 'ES-607', name: 'ES-607', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-7.jpg' },
  { ref: 'ES-608', name: 'ES-608', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-8.jpg' },
  { ref: 'ES-609', name: 'ES-609', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-9.jpg' },
  { ref: 'ES-610', name: 'ES-610', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-10.jpg' },
  { ref: 'ES-611', name: 'ES-611', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-11.jpg' },
  { ref: 'ES-612', name: 'ES-612', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-12.jpg' },
  { ref: 'ES-613', name: 'ES-613', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-13.jpg' },
  { ref: 'ES-614', name: 'ES-614', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-14.jpg' },
  { ref: 'ES-615', name: 'ES-615', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-15.jpg' },
  { ref: 'ES-616', name: 'ES-616', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-16.jpg' },
  { ref: 'ES-617', name: 'ES-617', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-17.jpg' },
  { ref: 'ES-618', name: 'ES-618', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-18.jpg' },
  { ref: 'ES-619', name: 'ES-619', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-19.jpg' },
  // Ventanales
  { ref: 'VT-509', name: 'VT-509', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-9.jpg' },
  { ref: 'VT-510', name: 'VT-510', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-10.jpg' },
  { ref: 'VT-502', name: 'VT-502', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-2.jpg' },
  { ref: 'VT-503', name: 'VT-503', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-3.jpg' },
  { ref: 'VT-504', name: 'VT-504', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-4.jpg' },
  { ref: 'VT-505', name: 'VT-505', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-5.jpg' },
  { ref: 'VT-506', name: 'VT-506', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-6.jpg' },
  { ref: 'VT-507', name: 'VT-507', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-7.jpg' },
  { ref: 'VT-508', name: 'VT-508', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-8.jpg' },
  { ref: 'VT-501', name: 'VT-501', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-1.jpg' },
  // Cubiertas y Marquesinas
  { ref: 'CU-701', name: 'CU-701', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-1.jpg' },
  { ref: 'CU-702', name: 'CU-702', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-2.jpg' },
  { ref: 'CU-703', name: 'CU-703', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-3.jpg' },
  { ref: 'CU-704', name: 'CU-704', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-4.jpg' },
  { ref: 'CU-705', name: 'CU-705', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-5.jpg' },
  { ref: 'CU-706', name: 'CU-706', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-6.jpg' },
  { ref: 'CU-707', name: 'CU-707', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-7.jpg' },
  { ref: 'CU-708', name: 'CU-708', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-8.jpg' },
  // Santamarías
  { ref: 'SM-801', name: 'SM-801', cat: 'santamarias', desc: '', img: 'assets/cat/santamarias/santamarias-1.jpg' },
  { ref: 'SM-802', name: 'SM-802', cat: 'santamarias', desc: '', img: 'assets/cat/santamarias/santamarias-2.jpg' },
  { ref: 'SM-803', name: 'SM-803', cat: 'santamarias', desc: '', img: 'assets/cat/santamarias/santamarias-3.jpg' },
  // Casilleros
  { ref: 'CS-601', name: 'CS-601', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-1.jpg' },
  { ref: 'CS-602', name: 'CS-602', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-2.jpg' },
  { ref: 'CS-603', name: 'CS-603', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-3.jpg' },
  { ref: 'CS-604', name: 'CS-604', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-4.jpg' },
  { ref: 'CS-605', name: 'CS-605', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-5.jpg' },
  { ref: 'CS-606', name: 'CS-606', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-6.jpg' },
  { ref: 'CS-607', name: 'CS-607', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-7.jpg' },
  { ref: 'CS-608', name: 'CS-608', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-8.jpg' },
  // Exhibidores
  { ref: 'EX-901', name: 'EX-901', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-1.jpg' },
  { ref: 'EX-902', name: 'EX-902', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-2.jpg' },
  { ref: 'EX-903', name: 'EX-903', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-3.jpg' },
  { ref: 'EX-904', name: 'EX-904', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-4.jpg' },
  { ref: 'EX-905', name: 'EX-905', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-5.jpg' },
  // Casetas y Comedores Metálicos
  { ref: 'CM-1001', name: 'CM-1001', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-1.jpg' },
  { ref: 'CM-1002', name: 'CM-1002', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-2.jpg' },
  { ref: 'CM-1003', name: 'CM-1003', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-3.jpg' },
  { ref: 'CM-1004', name: 'CM-1004', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-4.jpg' },
  { ref: 'CM-1005', name: 'CM-1005', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-5.jpg' },
  { ref: 'CM-1006', name: 'CM-1006', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-6.jpg' },
  { ref: 'CM-1007', name: 'CM-1007', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-7.jpg' },
  { ref: 'CM-1008', name: 'CM-1008', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-8.jpg' },
  { ref: 'CM-1009', name: 'CM-1009', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-9.jpg' },
  { ref: 'CM-1010', name: 'CM-1010', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-10.jpg' },
  { ref: 'CM-1011', name: 'CM-1011', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-11.jpg' },
  { ref: 'CM-1012', name: 'CM-1012', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-12.jpg' },
  // Estantes Metálicos
  { ref: 'ET-1101', name: 'ET-1101', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-1.jpg' },
  { ref: 'ET-1102', name: 'ET-1102', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-2.jpg' },
  { ref: 'ET-1103', name: 'ET-1103', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-3.jpg' },
  { ref: 'ET-1104', name: 'ET-1104', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-4.jpg' },
  { ref: 'ET-1105', name: 'ET-1105', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-5.jpg' },
  { ref: 'ET-1106', name: 'ET-1106', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-6.jpg' },
  { ref: 'ET-1107', name: 'ET-1107', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-7.jpg' },
];

export function categoryBySlug(slug) {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function designsByCategory(slug) {
  return DESIGNS.filter((d) => d.cat === slug);
}

export function categoryCover(slug) {
  const first = designsByCategory(slug)[0];
  return first ? first.img : null;
}
