/**
 * HERRE-COL — catalog data model.
 * Data-driven: add a category to CATEGORIES and designs to DESIGNS.
 * Every design belongs to a category by its `cat` slug — nothing else needs to change.
 *
 * Images are the real HERRE-COL product photos, organized under assets/cat/<categoria>/.
 */

export const CATEGORIES = [
  { slug: 'puertas', name: 'Puertas', icon: 'door-closed', tagline: 'El primer gesto de una fachada.' },
  { slug: 'ventanas', name: 'Ventanas', icon: 'app-window', tagline: 'Luz enmarcada con precisión.' },
  { slug: 'ventanales', name: 'Ventanales', icon: 'panels-top-left', tagline: 'Vidrio y acero de piso a techo.' },
  { slug: 'puertas-reja', name: 'Puertas Reja', icon: 'shield-half', tagline: 'Seguridad que se ve elegante.' },
  { slug: 'enrejados', name: 'Enrejados', icon: 'fence', tagline: 'Ritmo, línea y protección.' },
  { slug: 'portones', name: 'Portones', icon: 'warehouse', tagline: 'La entrada que impone respeto.' },
  { slug: 'escaleras', name: 'Escaleras y Pasamanos', icon: 'chevrons-up', tagline: 'Estructura convertida en escultura.' },
  { slug: 'cubiertas', name: 'Cubiertas y Marquesinas', icon: 'triangle', tagline: 'Sombra con intención arquitectónica.' },
  { slug: 'santamarias', name: 'Santamarías', icon: 'rows', tagline: 'Cierre seguro para locales y garajes.' },
  { slug: 'estantes', name: 'Estantes Metálicos', icon: 'library', tagline: 'Almacenamiento resistente y organizado.' },
  { slug: 'casilleros', name: 'Casilleros', icon: 'grid', tagline: 'Almacenamiento seguro en metal.' },
  { slug: 'exhibidores', name: 'Exhibidores', icon: 'shirt', tagline: 'Estructuras para exhibir tu producto.' },
  { slug: 'casetas-comedores', name: 'Casetas y Comedores Metálicos', icon: 'store', tagline: 'Espacios y mobiliario en metal a la medida.' },
];

export const DESIGNS = [
  // Puertas
  { ref: 'PT-101', name: 'PT-101', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-1.jpg' },
  { ref: 'PT-102', name: 'PT-102', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-2.jpg' },
  { ref: 'PT-103', name: 'PT-103', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-3.jpg' },
  { ref: 'PT-104', name: 'PT-104', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-4.jpg' },
  { ref: 'PT-105', name: 'PT-105', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-5.jpg' },
  { ref: 'PT-106', name: 'PT-106', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-6.jpg' },
  { ref: 'PT-107', name: 'PT-107', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-7.jpg' },
  { ref: 'PT-108', name: 'PT-108', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-8.jpg' },
  { ref: 'PT-109', name: 'PT-109', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-9.jpg' },
  { ref: 'PT-110', name: 'PT-110', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-10.jpg' },
  { ref: 'PT-111', name: 'PT-111', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-11.jpg' },
  { ref: 'PT-112', name: 'PT-112', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-12.jpg' },
  { ref: 'PT-113', name: 'PT-113', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-13.jpg' },
  { ref: 'PT-114', name: 'PT-114', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-14.jpg' },
  { ref: 'PT-115', name: 'PT-115', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-15.jpg' },
  { ref: 'PT-116', name: 'PT-116', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-16.jpg' },
  { ref: 'PT-117', name: 'PT-117', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-17.jpg' },
  { ref: 'PT-118', name: 'PT-118', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-18.jpg' },
  { ref: 'PT-119', name: 'PT-119', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-19.jpg' },
  { ref: 'PT-120', name: 'PT-120', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-20.jpg' },
  { ref: 'PT-121', name: 'PT-121', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-21.jpg' },
  { ref: 'PT-122', name: 'PT-122', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-22.jpg' },
  { ref: 'PT-123', name: 'PT-123', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-23.jpg' },
  { ref: 'PT-124', name: 'PT-124', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-24.jpg' },
  { ref: 'PT-125', name: 'PT-125', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-25.jpg' },
  { ref: 'PT-126', name: 'PT-126', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-26.jpg' },
  { ref: 'PT-127', name: 'PT-127', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-27.jpg' },
  { ref: 'PT-128', name: 'PT-128', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-28.jpg' },
  { ref: 'PT-129', name: 'PT-129', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-29.jpg' },
  { ref: 'PT-130', name: 'PT-130', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-30.jpg' },
  { ref: 'PT-131', name: 'PT-131', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-31.jpg' },
  { ref: 'PT-132', name: 'PT-132', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-32.jpg' },
  { ref: 'PT-133', name: 'PT-133', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-33.jpg' },
  { ref: 'PT-134', name: 'PT-134', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-34.jpg' },
  { ref: 'PT-135', name: 'PT-135', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-35.jpg' },
  { ref: 'PT-136', name: 'PT-136', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-36.jpg' },
  { ref: 'PT-137', name: 'PT-137', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-37.jpg' },
  { ref: 'PT-138', name: 'PT-138', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-38.jpg' },
  { ref: 'PT-139', name: 'PT-139', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-39.jpg' },
  { ref: 'PT-140', name: 'PT-140', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-40.jpg' },
  { ref: 'PT-141', name: 'PT-141', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-41.jpg' },
  { ref: 'PT-142', name: 'PT-142', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-42.jpg' },
  { ref: 'PT-143', name: 'PT-143', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-43.jpg' },
  { ref: 'PT-144', name: 'PT-144', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-44.jpg' },
  { ref: 'PT-145', name: 'PT-145', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-45.jpg' },
  { ref: 'PT-146', name: 'PT-146', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-46.jpg' },
  { ref: 'PT-147', name: 'PT-147', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-47.jpg' },
  { ref: 'PT-148', name: 'PT-148', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-48.jpg' },
  { ref: 'PT-149', name: 'PT-149', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-49.jpg' },
  { ref: 'PT-150', name: 'PT-150', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-50.jpg' },
  { ref: 'PT-151', name: 'PT-151', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-51.jpg' },
  { ref: 'PT-152', name: 'PT-152', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-52.jpg' },
  { ref: 'PT-153', name: 'PT-153', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-53.jpg' },
  { ref: 'PT-154', name: 'PT-154', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-54.jpg' },
  { ref: 'PT-155', name: 'PT-155', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-55.jpg' },
  { ref: 'PT-156', name: 'PT-156', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-56.jpg' },
  { ref: 'PT-157', name: 'PT-157', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-57.jpg' },
  { ref: 'PT-158', name: 'PT-158', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-58.jpg' },
  { ref: 'PT-159', name: 'PT-159', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-59.jpg' },
  { ref: 'PT-160', name: 'PT-160', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-60.jpg' },
  { ref: 'PT-161', name: 'PT-161', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-61.jpg' },
  { ref: 'PT-162', name: 'PT-162', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-62.jpg' },
  { ref: 'PT-163', name: 'PT-163', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-63.jpg' },
  { ref: 'PT-164', name: 'PT-164', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-64.jpg' },
  { ref: 'PT-165', name: 'PT-165', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-65.jpg' },
  { ref: 'PT-166', name: 'PT-166', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-66.jpg' },
  { ref: 'PT-167', name: 'PT-167', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-67.jpg' },
  { ref: 'PT-168', name: 'PT-168', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-68.jpg' },
  { ref: 'PT-169', name: 'PT-169', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-69.jpg' },
  { ref: 'PT-170', name: 'PT-170', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-70.jpg' },
  { ref: 'PT-171', name: 'PT-171', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-71.jpg' },
  { ref: 'PT-172', name: 'PT-172', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-72.jpg' },
  { ref: 'PT-173', name: 'PT-173', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-73.jpg' },
  { ref: 'PT-174', name: 'PT-174', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-74.jpg' },
  { ref: 'PT-175', name: 'PT-175', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-75.jpg' },
  { ref: 'PT-176', name: 'PT-176', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-76.jpg' },
  { ref: 'PT-177', name: 'PT-177', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-77.jpg' },
  { ref: 'PT-178', name: 'PT-178', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-78.jpg' },
  { ref: 'PT-179', name: 'PT-179', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-79.jpg' },
  { ref: 'PT-180', name: 'PT-180', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-80.jpg' },
  { ref: 'PT-181', name: 'PT-181', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-81.jpg' },
  { ref: 'PT-182', name: 'PT-182', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-82.jpg' },
  { ref: 'PT-183', name: 'PT-183', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-83.jpg' },
  { ref: 'PT-184', name: 'PT-184', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-84.jpg' },
  { ref: 'PT-185', name: 'PT-185', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-85.jpg' },
  { ref: 'PT-186', name: 'PT-186', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-86.jpg' },
  { ref: 'PT-187', name: 'PT-187', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-87.jpg' },
  { ref: 'PT-188', name: 'PT-188', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-88.jpg' },
  { ref: 'PT-189', name: 'PT-189', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-89.jpg' },
  { ref: 'PT-190', name: 'PT-190', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-90.jpg' },
  { ref: 'PT-191', name: 'PT-191', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-91.jpg' },
  { ref: 'PT-192', name: 'PT-192', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-92.jpg' },
  { ref: 'PT-193', name: 'PT-193', cat: 'puertas', desc: '', img: 'assets/cat/puertas/puertas-93.jpg' },
  // Enrejados
  { ref: 'EN-101', name: 'EN-101', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-1.jpg' },
  { ref: 'EN-102', name: 'EN-102', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-2.jpg' },
  { ref: 'EN-103', name: 'EN-103', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-3.jpg' },
  { ref: 'EN-104', name: 'EN-104', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-4.jpg' },
  { ref: 'EN-105', name: 'EN-105', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-5.jpg' },
  { ref: 'EN-106', name: 'EN-106', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-6.jpg' },
  { ref: 'EN-107', name: 'EN-107', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-7.jpg' },
  { ref: 'EN-108', name: 'EN-108', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-8.jpg' },
  { ref: 'EN-109', name: 'EN-109', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-9.jpg' },
  { ref: 'EN-110', name: 'EN-110', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-10.jpg' },
  { ref: 'EN-111', name: 'EN-111', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-11.jpg' },
  { ref: 'EN-112', name: 'EN-112', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-12.jpg' },
  { ref: 'EN-113', name: 'EN-113', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-13.jpg' },
  { ref: 'EN-114', name: 'EN-114', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-14.jpg' },
  { ref: 'EN-115', name: 'EN-115', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-15.jpg' },
  { ref: 'EN-116', name: 'EN-116', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-16.jpg' },
  { ref: 'EN-117', name: 'EN-117', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-17.jpg' },
  { ref: 'EN-118', name: 'EN-118', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-18.jpg' },
  { ref: 'EN-119', name: 'EN-119', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-19.jpg' },
  { ref: 'EN-120', name: 'EN-120', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-20.jpg' },
  { ref: 'EN-121', name: 'EN-121', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-21.jpg' },
  { ref: 'EN-122', name: 'EN-122', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-22.jpg' },
  { ref: 'EN-123', name: 'EN-123', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-23.jpg' },
  { ref: 'EN-124', name: 'EN-124', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-24.jpg' },
  { ref: 'EN-125', name: 'EN-125', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-25.jpg' },
  { ref: 'EN-126', name: 'EN-126', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-26.jpg' },
  { ref: 'EN-127', name: 'EN-127', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-27.jpg' },
  { ref: 'EN-128', name: 'EN-128', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-28.jpg' },
  { ref: 'EN-129', name: 'EN-129', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-29.jpg' },
  { ref: 'EN-130', name: 'EN-130', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-30.jpg' },
  { ref: 'EN-131', name: 'EN-131', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-31.jpg' },
  { ref: 'EN-132', name: 'EN-132', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-32.jpg' },
  { ref: 'EN-133', name: 'EN-133', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-33.jpg' },
  { ref: 'EN-134', name: 'EN-134', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-34.jpg' },
  { ref: 'EN-135', name: 'EN-135', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-35.jpg' },
  { ref: 'EN-136', name: 'EN-136', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-36.jpg' },
  { ref: 'EN-137', name: 'EN-137', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-37.jpg' },
  { ref: 'EN-138', name: 'EN-138', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-38.jpg' },
  { ref: 'EN-139', name: 'EN-139', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-39.jpg' },
  { ref: 'EN-140', name: 'EN-140', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-40.jpg' },
  { ref: 'EN-141', name: 'EN-141', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-41.jpg' },
  { ref: 'EN-142', name: 'EN-142', cat: 'enrejados', desc: '', img: 'assets/cat/enrejados/enrejados-42.jpg' },
  // Ventanas
  { ref: 'VN-101', name: 'VN-101', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-1.jpg' },
  { ref: 'VN-102', name: 'VN-102', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-2.jpg' },
  { ref: 'VN-103', name: 'VN-103', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-3.jpg' },
  { ref: 'VN-104', name: 'VN-104', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-4.jpg' },
  { ref: 'VN-105', name: 'VN-105', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-5.jpg' },
  { ref: 'VN-106', name: 'VN-106', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-6.jpg' },
  { ref: 'VN-107', name: 'VN-107', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-7.jpg' },
  { ref: 'VN-108', name: 'VN-108', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-8.jpg' },
  { ref: 'VN-109', name: 'VN-109', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-9.jpg' },
  { ref: 'VN-110', name: 'VN-110', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-10.jpg' },
  { ref: 'VN-111', name: 'VN-111', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-11.jpg' },
  { ref: 'VN-112', name: 'VN-112', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-12.jpg' },
  { ref: 'VN-113', name: 'VN-113', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-13.jpg' },
  { ref: 'VN-114', name: 'VN-114', cat: 'ventanas', desc: '', img: 'assets/cat/ventanas/ventanas-14.jpg' },
  // Ventanales
  { ref: 'VT-101', name: 'VT-101', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-1.jpg' },
  { ref: 'VT-102', name: 'VT-102', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-2.jpg' },
  { ref: 'VT-103', name: 'VT-103', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-3.jpg' },
  { ref: 'VT-104', name: 'VT-104', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-4.jpg' },
  { ref: 'VT-105', name: 'VT-105', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-5.jpg' },
  { ref: 'VT-106', name: 'VT-106', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-6.jpg' },
  { ref: 'VT-107', name: 'VT-107', cat: 'ventanales', desc: '', img: 'assets/cat/ventanales/ventanales-7.jpg' },
  // Portones
  { ref: 'PO-101', name: 'PO-101', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-1.jpg' },
  { ref: 'PO-102', name: 'PO-102', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-2.jpg' },
  { ref: 'PO-103', name: 'PO-103', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-3.jpg' },
  { ref: 'PO-104', name: 'PO-104', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-4.jpg' },
  { ref: 'PO-105', name: 'PO-105', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-5.jpg' },
  { ref: 'PO-106', name: 'PO-106', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-6.jpg' },
  { ref: 'PO-107', name: 'PO-107', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-7.jpg' },
  { ref: 'PO-108', name: 'PO-108', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-8.jpg' },
  { ref: 'PO-109', name: 'PO-109', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-9.jpg' },
  { ref: 'PO-110', name: 'PO-110', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-10.jpg' },
  { ref: 'PO-111', name: 'PO-111', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-11.jpg' },
  { ref: 'PO-112', name: 'PO-112', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-12.jpg' },
  { ref: 'PO-113', name: 'PO-113', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-13.jpg' },
  { ref: 'PO-114', name: 'PO-114', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-14.jpg' },
  { ref: 'PO-115', name: 'PO-115', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-15.jpg' },
  { ref: 'PO-116', name: 'PO-116', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-16.jpg' },
  { ref: 'PO-117', name: 'PO-117', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-17.jpg' },
  { ref: 'PO-118', name: 'PO-118', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-18.jpg' },
  { ref: 'PO-119', name: 'PO-119', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-19.jpg' },
  { ref: 'PO-120', name: 'PO-120', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-20.jpg' },
  { ref: 'PO-121', name: 'PO-121', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-21.jpg' },
  { ref: 'PO-122', name: 'PO-122', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-22.jpg' },
  { ref: 'PO-123', name: 'PO-123', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-23.jpg' },
  { ref: 'PO-124', name: 'PO-124', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-24.jpg' },
  { ref: 'PO-125', name: 'PO-125', cat: 'portones', desc: '', img: 'assets/cat/portones/portones-25.jpg' },
  // Puertas Reja
  { ref: 'PR-101', name: 'PR-101', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-1.jpg' },
  { ref: 'PR-102', name: 'PR-102', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-2.jpg' },
  { ref: 'PR-103', name: 'PR-103', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-3.jpg' },
  { ref: 'PR-104', name: 'PR-104', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-4.jpg' },
  { ref: 'PR-105', name: 'PR-105', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-5.jpg' },
  { ref: 'PR-106', name: 'PR-106', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-6.jpg' },
  { ref: 'PR-107', name: 'PR-107', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-7.jpg' },
  { ref: 'PR-108', name: 'PR-108', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-8.jpg' },
  { ref: 'PR-109', name: 'PR-109', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-9.jpg' },
  { ref: 'PR-110', name: 'PR-110', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-10.jpg' },
  { ref: 'PR-111', name: 'PR-111', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-11.jpg' },
  { ref: 'PR-112', name: 'PR-112', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-12.jpg' },
  { ref: 'PR-113', name: 'PR-113', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-13.jpg' },
  { ref: 'PR-114', name: 'PR-114', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-14.jpg' },
  { ref: 'PR-115', name: 'PR-115', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-15.jpg' },
  { ref: 'PR-116', name: 'PR-116', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-16.jpg' },
  { ref: 'PR-117', name: 'PR-117', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-17.jpg' },
  { ref: 'PR-118', name: 'PR-118', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-18.jpg' },
  { ref: 'PR-119', name: 'PR-119', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-19.jpg' },
  { ref: 'PR-120', name: 'PR-120', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-20.jpg' },
  { ref: 'PR-121', name: 'PR-121', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-21.jpg' },
  { ref: 'PR-122', name: 'PR-122', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-22.jpg' },
  { ref: 'PR-123', name: 'PR-123', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-23.jpg' },
  { ref: 'PR-124', name: 'PR-124', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-24.jpg' },
  { ref: 'PR-125', name: 'PR-125', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-25.jpg' },
  { ref: 'PR-126', name: 'PR-126', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-26.jpg' },
  { ref: 'PR-127', name: 'PR-127', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-27.jpg' },
  { ref: 'PR-128', name: 'PR-128', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-28.jpg' },
  { ref: 'PR-129', name: 'PR-129', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-29.jpg' },
  { ref: 'PR-130', name: 'PR-130', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-30.jpg' },
  { ref: 'PR-131', name: 'PR-131', cat: 'puertas-reja', desc: '', img: 'assets/cat/puertas-reja/puertas-reja-31.jpg' },
  // Escaleras y Pasamanos
  { ref: 'ES-101', name: 'ES-101', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-1.jpg' },
  { ref: 'ES-102', name: 'ES-102', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-2.jpg' },
  { ref: 'ES-103', name: 'ES-103', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-3.jpg' },
  { ref: 'ES-104', name: 'ES-104', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-4.jpg' },
  { ref: 'ES-105', name: 'ES-105', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-5.jpg' },
  { ref: 'ES-106', name: 'ES-106', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-6.jpg' },
  { ref: 'ES-107', name: 'ES-107', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-7.jpg' },
  { ref: 'ES-108', name: 'ES-108', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-8.jpg' },
  { ref: 'ES-109', name: 'ES-109', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-9.jpg' },
  { ref: 'ES-110', name: 'ES-110', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-10.jpg' },
  { ref: 'ES-111', name: 'ES-111', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-11.jpg' },
  { ref: 'ES-112', name: 'ES-112', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-12.jpg' },
  { ref: 'ES-113', name: 'ES-113', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-13.jpg' },
  { ref: 'ES-114', name: 'ES-114', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-14.jpg' },
  { ref: 'ES-115', name: 'ES-115', cat: 'escaleras', desc: '', img: 'assets/cat/escaleras/escaleras-15.jpg' },
  // Cubiertas y Marquesinas
  { ref: 'CU-101', name: 'CU-101', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-1.jpg' },
  { ref: 'CU-102', name: 'CU-102', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-2.jpg' },
  { ref: 'CU-103', name: 'CU-103', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-3.jpg' },
  { ref: 'CU-104', name: 'CU-104', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-4.jpg' },
  { ref: 'CU-105', name: 'CU-105', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-5.jpg' },
  { ref: 'CU-106', name: 'CU-106', cat: 'cubiertas', desc: '', img: 'assets/cat/cubiertas/cubiertas-6.jpg' },
  // Santamarías
  { ref: 'SM-101', name: 'SM-101', cat: 'santamarias', desc: '', img: 'assets/cat/santamarias/santamarias-1.jpg' },
  { ref: 'SM-102', name: 'SM-102', cat: 'santamarias', desc: '', img: 'assets/cat/santamarias/santamarias-2.jpg' },
  { ref: 'SM-103', name: 'SM-103', cat: 'santamarias', desc: '', img: 'assets/cat/santamarias/santamarias-3.jpg' },
  // Estantes Metálicos
  { ref: 'ET-101', name: 'ET-101', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-1.jpg' },
  { ref: 'ET-102', name: 'ET-102', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-2.jpg' },
  { ref: 'ET-103', name: 'ET-103', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-3.jpg' },
  { ref: 'ET-104', name: 'ET-104', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-4.jpg' },
  { ref: 'ET-105', name: 'ET-105', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-5.jpg' },
  { ref: 'ET-106', name: 'ET-106', cat: 'estantes', desc: '', img: 'assets/cat/estantes/estantes-6.jpg' },
  // Casilleros
  { ref: 'CS-101', name: 'CS-101', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-1.jpg' },
  { ref: 'CS-102', name: 'CS-102', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-2.jpg' },
  { ref: 'CS-103', name: 'CS-103', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-3.jpg' },
  { ref: 'CS-104', name: 'CS-104', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-4.jpg' },
  { ref: 'CS-105', name: 'CS-105', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-5.jpg' },
  { ref: 'CS-106', name: 'CS-106', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-6.jpg' },
  { ref: 'CS-107', name: 'CS-107', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-7.jpg' },
  { ref: 'CS-108', name: 'CS-108', cat: 'casilleros', desc: '', img: 'assets/cat/casilleros/casilleros-8.jpg' },
  // Casetas y Comedores Metálicos
  { ref: 'CM-101', name: 'CM-101', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-1.jpg' },
  { ref: 'CM-102', name: 'CM-102', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-2.jpg' },
  { ref: 'CM-103', name: 'CM-103', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-3.jpg' },
  { ref: 'CM-104', name: 'CM-104', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-4.jpg' },
  { ref: 'CM-105', name: 'CM-105', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-5.jpg' },
  { ref: 'CM-106', name: 'CM-106', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-6.jpg' },
  { ref: 'CM-107', name: 'CM-107', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-7.jpg' },
  { ref: 'CM-108', name: 'CM-108', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-8.jpg' },
  { ref: 'CM-109', name: 'CM-109', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-9.jpg' },
  { ref: 'CM-110', name: 'CM-110', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-10.jpg' },
  { ref: 'CM-111', name: 'CM-111', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-11.jpg' },
  { ref: 'CM-112', name: 'CM-112', cat: 'casetas-comedores', desc: '', img: 'assets/cat/casetas-comedores/casetas-comedores-12.jpg' },
  // Exhibidores
  { ref: 'EX-101', name: 'EX-101', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-1.jpg' },
  { ref: 'EX-102', name: 'EX-102', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-2.jpg' },
  { ref: 'EX-103', name: 'EX-103', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-3.jpg' },
  { ref: 'EX-104', name: 'EX-104', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-4.jpg' },
  { ref: 'EX-105', name: 'EX-105', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-5.jpg' },
  { ref: 'EX-106', name: 'EX-106', cat: 'exhibidores', desc: '', img: 'assets/cat/exhibidores/exhibidores-6.jpg' },
];

export function categoryBySlug(slug) {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function designsByCategory(slug) {
  return DESIGNS.filter((d) => d.cat === slug);
}

export function categoryCover(slug) {
  const first = designsByCategory(slug)[0];
  return first ? first.img : null;
}
